server:
  port: 8000
  servlet:
    context-path: /practice-producer

spring:
  rabbitmq:
    addresses: localhost:8071,localhost:8072,localhost:8073
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true