spring:
  rabbitmq:
# 单机配置
#    host: 36.137.128.27
#    port: 5672
    #集群配置
    addresses: 36.137.128.27:8071,36.137.128.27:8072,36.137.128.27:8073
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true
